workflows:
  ios-release-player:
    name: iOS Release Build - Player
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: 3.35.4
      xcode: latest

    scripts:
      - name: Prepare & get packages
        script: |
          set -e
          flutter clean
          flutter pub get
          flutter precache --ios

      - name: Build iOS IPA (unsigned, hello target)
        script: |
          set -e
          flutter build ipa --release --no-codesign -t lib/hello_ios.dart

      # ⬇️ خطوة فحص الـ IPA
      - name: Inspect IPA contents
        script: |
          set -e
          IPA=$(ls build/ios/ipa/*.ipa | head -n1)
          echo "Using IPA: $IPA"
          rm -rf ipa_unzip && mkdir ipa_unzip
          unzip -q "$IPA" -d ipa_unzip
          echo "=== Tree ==="
          find ipa_unzip -maxdepth 4 -print
          echo "=== Check essentials ==="
          test -d ipa_unzip/Payload/Runner.app/Frameworks/Flutter.framework
          test -d ipa_unzip/Payload/Runner.app/Frameworks/App.framework/flutter_assets
          test -f ipa_unzip/Payload/Runner.app/Info.plist
          echo "IPA looks complete ✅"

    artifacts:
      - build/ios/ipa/*.ipa
      - ipa_unzip/**

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
