workflows:
  ios-release-player:
    name: iOS Release Build - Player
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: 3.35.4
      xcode: latest

    scripts:
      - name: Prepare & get packages
        script: |
          set -e
          flutter clean
          flutter pub get
          flutter precache --ios

      - name: Build iOS IPA (unsigned, hello target)
        script: |
          set -e
          flutter build ipa --release --no-codesign -t lib/hello_ios.dart
          echo "Artifacts in build/ios/ipa:"
          ls -la build/ios/ipa || true
          echo "Archive in build/ios/archive:"
          ls -la build/ios/archive || true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app
      - build/ios/archive/*.xcarchive

    publishing:
      email:
        recipients:
          - ahmed.289ahmed@gmail.com
