name: var_player
description: "VAR Player - مشغل خارجي للقنوات"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  media_kit: ^1.1.10
  media_kit_video: ^1.1.10
  media_kit_libs_android_video: ^1.3.7   # Android
  media_kit_libs_ios_video: ^1.1.4       # iOS (إذا تحتاج مستقبلاً)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
